Fix alignment selection for GroupButton in FSE
Codeinwp/otter-blocks pull request #1084
Opened 2022-08-04 07:06 UTC by Soare-Robert-Daniel

Closes #1078.

### Summary

Remade the alignment selector to something that can work in FSE.

### Screenshots 

![image](https://user-images.githubusercontent.com/17597852/182784876-565297cb-ccb9-4abb-8c6c-51ebb9e50614.png)

----

### Test instructions

1. Insert a Button Group block
2. Check the Alignment in inspector

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

2022-08-04 14:12 UTC, HardeepAsrani requested changes
Neither of these seems to be available in WP 5.8

2022-08-09 11:54 UTC, Soare-Robert-Daniel commented
Current look:

![image](https://user-images.githubusercontent.com/17597852/183640915-43f65270-ccf8-4227-af8e-0bb7d2fb6ee2.png)

2022-08-10 08:02 UTC, irinelenache commented
@Soare-Robert-Daniel The alignment problem is fixed for me, but found another problem:

- [ ] Creating a **Button group** block without making any change to the styles, will look different in frontend
editor: https://vertis.d.pr/Glg1bu
frontend: https://vertis.d.pr/oC7AWQ

You can check it on this instance:
```
 Admin area URL: https://jazzycolor.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: Pxah1tQhSi0 
```

2022-08-10 08:16 UTC, Soare-Robert-Daniel commented
@irinelenache that will be an FSE problem (I will make an issue for it). I don't know why it is happening. Seams to be a problem with the core for not loading some assets for Button, specifically `wp-block-button`. 

@HardeepAsrani, if we use a class from Gutenberg, we need to load their CSS for FSE. Group Button will not work until you put a core button on the page to load the CSS for `wp-block-button`.

2022-08-10 08:30 UTC, Soare-Robert-Daniel commented
> @irinelenache that will be an FSE problem (I will make an issue for it #1106). Seams to be a problem with the core for not loading some assets for Button, specifically `wp-block-button`.
> 
> @HardeepAsrani, if we use a class from Gutenberg, we need to load their CSS for FSE. Group Button will not work until you put a core button on the page to load the CSS for `wp-block-button`.

2022-08-11 09:41 UTC, merged