Add description for each feature in the review block
Codeinwp/otter-blocks pull request #1426
Opened 2023-01-04 18:17 UTC by arinaturcu

Closes #1260.

### Summary

Add a description for each feature of the product in the Review Block, under the review.

### Screenshots 
<img width="375" alt="Screenshot 2023-01-04 at 20 15 32" src="https://user-images.githubusercontent.com/39873395/210622195-f2cbec67-d012-45c8-b619-0b9016cb0732.png">

----

### Test instructions

- In the `Product Features` panel, when a feature is clicked, the text area for the description should appear under the `rating` control.
- It will inherit the text color, and will have `0.7 opacity` and `80% font size` of the feature title font size (which is the content font size)
- we need to make sure it looks ok with both styles (One Column and Two Columns)

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

2023-01-04 20:13 UTC, HardeepAsrani commented on src/blocks/blocks/review/block.json
> +				"description": "Good price for the quality"
You don't need to add them by default.

2023-01-04 20:14 UTC, HardeepAsrani commented on src/blocks/blocks/review/edit.js
> +
You can make sure it doesn't appear if the block isn't selected.

2023-01-04 20:15 UTC, HardeepAsrani requested changes
We can remove the description by default and also make sure it doesn't appear in editor if it's empty and the block isn't selected.

2023-01-05 18:52 UTC, HardeepAsrani approved these changes

2023-01-06 09:14 UTC, irinelenache commented
@arinaturcu Tested and everything works fine on my end 🚀

2023-01-06 11:49 UTC, merged