Fix: Additional classes behavior when deleting ticss class
Codeinwp/otter-blocks pull request #1518
Opened 2023-02-26 14:44 UTC by arinaturcu

Closes #1507.

### Summary

- When trying to delete the `ticss` class with backspace from the `Additional Classes`, the input is filled with `ticss` strings (see [here](https://www.loom.com/share/0bbaa6e047f44042811384bc7429e755)).
- This PR lets the user delete the class (meaning that the `Custom CSS` is no longer applied) until the `Custom CSS` is modified, which causes the `ticss` class to be added again.

### Screenshots 

----

### Test instructions

- Add Custom CSS to a block.
- From the Advance tab, try to remove the CSS class by pressing backspace
- Modify the Custom CSS and the class should be added again.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

2023-02-27 11:22 UTC, HardeepAsrani approved these changes

2023-02-27 18:33 UTC, HardeepAsrani requested changes
<img width="978" alt="Screenshot 2023-02-28 at 12 03 00 AM" src="https://user-images.githubusercontent.com/2649903/221652395-4c954a16-c7bf-46a4-a648-d4c6668b6f35.png">

Just as I try to type something, I get this error and the editor breaks.

2023-03-02 01:59 UTC, HardeepAsrani approved these changes

2023-03-02 09:42 UTC, irinelenache commented
@arinaturcu Tested and the issue is fixed by the PR 👍

2023-03-02 18:46 UTC, merged