Add development guideline and docs
Codeinwp/otter-blocks pull request #1552
Opened 2023-03-10 09:18 UTC by Soare-Robert-Daniel

Closes #.

### Summary

### Screenshots 

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

2023-04-03 14:52 UTC, HardeepAsrani commented
Looks good, it can have a section about the feature-plugin, as in Blocks CSS/Animation and so on.

2023-04-12 18:18 UTC, HardeepAsrani requested changes
Apart from that, few things we can mention:

- We can mention CSS Utility class.
- We can mention how to add new patterns.

2023-04-12 18:18 UTC, HardeepAsrani commented on docs/woocommerce-extensions.md
> +- Woo Comparison Block
We don't have it anymore, it's part of Sparks now.

2023-04-20 06:04 UTC, arinaturcu approved these changes
Looks good 👍🏻

2023-05-10 11:15 UTC, merged