Add Popup Variations
Codeinwp/otter-blocks pull request #1555
Opened 2023-03-13 11:27 UTC by Soare-Robert-Daniel

Closes #1495.

### Summary

Add two popups variations for free users:
- Popup with Image and Text
- Popup with Form

### Screenshots 

![image](https://user-images.githubusercontent.com/17597852/224688604-6364c020-c337-4e3d-94de-c9ecd2f006c1.png)

----

### Test instructions

1. Insert a Popup.
2. Test each variation.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

2023-03-13 11:59 UTC, Soare-Robert-Daniel commented
@HardeepAsrani @mghenciu I think we should change the usage of Neve CSS variables for Popup variantions.

The variations look awful on other themes.

https://user-images.githubusercontent.com/17597852/224695628-ab90a192-1ca5-4ea6-a845-b399f55a8163.mp4

2023-03-13 12:01 UTC, HardeepAsrani commented
I think the same is for Countdown Patterns where we are using Neve variables: https://github.com/Codeinwp/store-themeisle/pull/501

I think in other Patterns we weren't using Neve colors but solid ones.

2023-03-13 12:02 UTC, Soare-Robert-Daniel commented
@mghenciu, you can download the build from [here](https://github.com/Codeinwp/otter-blocks/pull/1555#issuecomment-1465977961) to test. Also, you put some defined colors in the popups, and then you can send me the instance to update 👌

2023-03-13 12:02 UTC, HardeepAsrani requested changes
We can review it once we've fixed the design issues.

2023-03-13 17:44 UTC, mghenciu commented
Looks good, @Soare-Robert-Daniel .

First thing we can do is to remove the border, and change the color a the Otter Icons color. Because otherwise the icons look like they are not from Otter( sorry for not thinking about this in the first place). Did the changes in Figma:
![image](https://user-images.githubusercontent.com/52494172/224761212-cd00bad9-32f6-4a37-adf8-7b9704c98bb4.png)


___
Regarding the colors, you can remove them (overline for example), the Popup top border can be either Otter accent or just text color; and for the buttons they should act as other buttons that we have in patterns.

I've did some fixes [here](https://demosites.io/otter/pro-patterns/), mainly:
- added hardcoded color for the Background
- same for the border
- added shadow to increase visibility
- changed the font size for the Title

**And this should be fine with different themes: Astra, Kadence, 2020**

https://user-images.githubusercontent.com/52494172/224784111-9e6cec6f-6fc3-4ab3-98ec-fd357211ab1d.mov
___


https://user-images.githubusercontent.com/52494172/224784204-d9e3834b-ec40-4a9d-ac0e-e41d640a2f02.mov


___

https://user-images.githubusercontent.com/52494172/224784251-cd021fa2-c353-48e2-8055-6915c5f0bec2.mov

2023-03-14 18:44 UTC, HardeepAsrani commented
@Soare-Robert-Daniel Can you make these changes with colors here as well? https://github.com/Codeinwp/store-themeisle/pull/501

2023-03-14 19:02 UTC, HardeepAsrani approved these changes

2023-03-14 19:02 UTC, merged