Form Storing Emails
Codeinwp/otter-blocks pull request #1571
Opened 2023-03-24 16:40 UTC by arinaturcu

Closes #.

### Summary

### Screenshots 

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

2023-04-17 13:44 UTC, HardeepAsrani commented on inc/plugins/class-dashboard.php
> +use function Sodium\add;
@arinaturcu is this added by VSCode's autocompletion?

2023-05-02 19:38 UTC, HardeepAsrani requested changes
For some reason, I see these two Pro areas even while using the Pro version:

<img width="2559" alt="Screenshot 2023-05-03 at 1 04 59 AM" src="https://user-images.githubusercontent.com/2649903/235767759-8aa3c629-3ab4-47a1-80d2-4f268ccb28cd.png">

For now, we don't have any option to disable the form submission? Just asking, we can add that option later when Robert's Form work is also done to avoid conflicts.

2023-05-02 19:42 UTC, HardeepAsrani commented on plugins/otter-pro/inc/plugins/form/class-form-submissions.php
> +			$bulk_actions['trash'] = 'Move to Trash';
Here you need to use i18n functions.

2023-05-02 19:51 UTC, HardeepAsrani commented on plugins/otter-pro/inc/plugins/form/class-form-submissions.php
> +		register_post_type(
One major issue right now that I see is that any user even with the role of Contributor can access this Dashboard. We should limit it to only people with admin capabilities.

2023-05-02 19:52 UTC, HardeepAsrani commented on plugins/otter-pro/inc/plugins/form/class-form-submissions.php
> +		register_post_type(
If you're using a role lower than Admin, you can visit the Dashboard by accessing the URl directly.

2023-05-03 10:29 UTC, arinaturcu commented
Thanks, @HardeepAsrani!
I fixed those and gave capabilities only to the administrator role. Let me know if you find anything else.

2023-05-03 20:31 UTC, HardeepAsrani approved these changes
Looks pretty great.

2023-05-05 08:53 UTC, rodica-andronache commented
@arinaturcu I've used the development versions https://vertis.d.pr/i/8sUE5X ( let me know if that's ok )

For Otter (free) I noticed that the form submissions page is not responsive https://vertis.d.pr/i/x7974m as is the main Otter page

When installing Otter Pro I got a fatal error https://vertis.d.pr/i/xWZffT so I've put the testing on hold

2023-05-08 07:32 UTC, arinaturcu commented
Thanks @rodica-andronache! It should work fine now 😄
Also, the free form submissions page is responsive now.

2023-05-09 08:01 UTC, rodica-andronache commented
@arinaturcu here are my findings. Thank you!

- [ ] Click on View submission -> than try to **Move to trash** -> Is not working https://vertis.d.pr/v/dZqnE8

- [ ] If the Email **Label** is empty ( and I’m using just the **Placeholder** for example ), the submission is not recorded  https://vertis.d.pr/i/oniQGF

- [ ] Similar for other fields, for e.g if I have a Textarea without a Label ( using just the Placeholder ), that field is not registered in the submission

- [ ] After a submission is created, if you go ahead and change the **Permalinks**, the link for the Post ( From where the form submission is coming from ) is not working anymore ( as it doesn’t get updated based on the Permalinks ) https://vertis.d.pr/v/8Vq1mR

- [ ] The fields from the submissions are not that responsive https://vertis.d.pr/i/AN3NTv ( compared to the PODs plugin for example )

2023-05-10 17:15 UTC, arinaturcu commented
@HardeepAsrani I see that the issue found by Rodica comes from here, and seems intentional. Is this right, or can I just save the input with `'(No label)'` as the label? What is the reason behind checking it?
https://github.com/Codeinwp/otter-blocks/blob/d4da09f67f35ebfc4f818a997601552e0a8f713b/src/blocks/frontend/form/index.js#L37-L45

2023-05-10 17:24 UTC, HardeepAsrani commented
@Soare-Robert-Daniel do you have any context to add here?

2023-05-11 09:02 UTC, Soare-Robert-Daniel commented
> @Soare-Robert-Daniel do you have any context to add here?

I did not consider fields without a Label as valid fields. 

@arinaturcu You can remove the `&& valueElem?.value` and add a default value.

2023-05-15 15:32 UTC, arinaturcu commented on plugins/otter-pro/inc/plugins/class-form-emails-storing.php
> +		);
This sounds really good 👍🏻

2023-05-19 10:51 UTC, Soare-Robert-Daniel commented
@Codeinwp/qa-team, for Otter this PR will be a priority 🙏 

Things added:
- Choose save location: Database (the Submissions menu), Email Only, Database and Email
- File field integration: You should see links and images when you submit some files.

:warning: When upgrading to Otter Pro, the email will set to be saved on submission instead of keep being sent as email.

⚠️ Functionality must be a priority. Things should work as expected. Details regarding stylistics are non-blocker; you can mention them, but depending on complexity they might not be addressed on this PR.

🔴 This will go through multiple rounds of testing.

## Screenshots

### Choose Location

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/56f0e68e-e90a-407d-8ed0-9da329592484)

### Files saved on submission

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/6fd632be-fe29-4038-aebf-79e87f5d725f)

2023-05-22 11:12 UTC, irinelenache commented
@Soare-Robert-Daniel Tested and the issues mentioned by Rodica are fixed, thank you 🚀 

I have only one question:

If you have multiple files attached in the form (3 in my example), there will be 4 entries in the database https://vertis.d.pr/i/W77Tpq . Is this expected?

2023-05-22 11:34 UTC, Soare-Robert-Daniel commented
@irinelenache, it is ok if you used Save to the Media Library. What you see are the attachments generated for the images.

2023-05-22 11:44 UTC, irinelenache commented
@Soare-Robert-Daniel Thank you for checking 🙏 I'll move this to **Ready to merge** as everything's fine here 🚀

2023-05-22 12:16 UTC, merged