Add Inspector notice when reCaptcha is active.
Codeinwp/otter-blocks pull request #1598
Opened 2023-04-06 12:45 UTC by Soare-Robert-Daniel

Closes #1574.

### Summary

Added a little notice to inform the user about the location of the API Keys.

### Screenshots 

![image](https://user-images.githubusercontent.com/17597852/230379861-a4fa752e-f5c4-4a37-b3cd-fb8e7740b1b6.png)

----

### Test instructions

ℹ️ API Keys are optional for testing this. You can use any value when it asks to introduce them. In Editor, we are just checking if the values are set.

1. Create a form block.
2. Activate the reCaptcha in Inspector.
3. Check the Inspector for the notice.

https://user-images.githubusercontent.com/17597852/230382084-75a68ef9-6eee-4739-9b30-bebd9711e5d8.mp4

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

2023-04-07 21:50 UTC, HardeepAsrani requested changes

2023-04-07 21:50 UTC, HardeepAsrani commented on src/blocks/blocks/form/inspector.js
> +							<ExternalLink href={ ( window?.location.origin ?? '' ) + '/wp-admin/options-general.php?page=otter' }>{ __( 'Go to Dashboard.', 'otter-blocks' ) }</ExternalLink>
It looks good, just a small change.We can replace it with `window.themeisleGutenberg.optionsPath`

2023-04-10 17:43 UTC, HardeepAsrani approved these changes

2023-04-11 07:55 UTC, Soare-Robert-Daniel commented
@rodica-andronache, thanks for pointing it out. I made the changes.

![image](https://user-images.githubusercontent.com/17597852/231093117-09130735-65c5-416a-9b6d-14cb147d42b0.png)

Also, no need to re-test this tiny change; I will move it `Ready to merge` (you can re-test if you disagree with this decision).

2023-04-11 22:44 UTC, merged