feat: Stripe API change in Editor
Codeinwp/otter-blocks pull request #1654
Opened 2023-05-04 11:13 UTC by Soare-Robert-Daniel

Closes #1609 .

### Summary

Instead of redirecting the user to Dashboard, allow it to change the API Key in Editor like in Google Maps.

### Screenshots 

https://user-images.githubusercontent.com/17597852/236187462-0e3ced5a-3803-41fb-82f3-656a4081f3ef.mp4

----

### Test instructions

⚠️ Make sure to have a Stripe API Key and some test products!

Follow the steps in the video and make sure that:
- It is not stuck; if you put in a valid API Key and refresh the page, the products selection will appear or the products themselves (if they were already selected)
- You can NOT find the correct API Key. There should be NO method to see the **VALID** API Key.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

2023-05-04 23:15 UTC, HardeepAsrani reviewed
Is it not possible to find out if the key is valid or not without refreshing the page? I'm testing with the first time where you add it to the placeholder and asks you to refresh the key. Works out too if you just switch between Text/Rich editor.

2023-05-05 06:58 UTC, Soare-Robert-Daniel commented
@HardeepAsrani 
In my testing, no; you made the `store` from which it pulls the data it does not refresh when the key is changed. The effect is only visible only when refreshing.

https://github.com/Codeinwp/otter-blocks/blob/61fd856e763f895cfe3692c3ed90e57ff18c7bad/inc/plugins/class-stripe-api.php#L47-L53

The refresh message is just a workaround to hide the error of an invalid key from the product store because it is still using the old API key.

2023-05-08 05:51 UTC, HardeepAsrani commented
@Soare-Robert-Daniel This can be solved by moving this part inside the rest requests: https://github.com/Codeinwp/otter-blocks/blob/61fd856e763f895cfe3692c3ed90e57ff18c7bad/inc/server/class-stripe-server.php#L49

2023-05-08 09:23 UTC, Soare-Robert-Daniel commented
@HardeepAsrani I couldn't make it work with just that. 

Analyzing with the debugger, the request for products is only made at loading. The products that are requested are loaded from the store cache

https://github.com/Codeinwp/otter-blocks/blob/88bfa59511714bc08e91234f92a93d5909f3549f/src/blocks/plugins/data/index.js#L143C1-L145

Should we implement a cache/state reset for it?

2023-05-08 15:39 UTC, HardeepAsrani commented
@Soare-Robert-Daniel Yea, when API is changed, we reset them back to default.

2023-05-10 06:23 UTC, HardeepAsrani commented
I put the API key and save, a don't get anything just see this input appear again.

<img width="1680" alt="Screenshot 2023-05-10 at 11 53 04 AM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/5753d291-859b-425c-a379-dd913176ce78">

2023-05-15 13:52 UTC, HardeepAsrani requested changes
Few small changes but rest looks good to go.

2023-05-15 13:52 UTC, HardeepAsrani commented on inc/server/class-stripe-server.php
> +		$this->stripe = new Stripe_API();
This can be a locally scoped variable now that we are using different instances of the class.

2023-05-15 13:52 UTC, HardeepAsrani commented on src/blocks/blocks/stripe-checkout/edit.tsx
> +					instructions={ ( hasProductsRequestFailed && productsError?.message ) || ( hasPricesRequestFailed && pricesError?.message ) || ( hasPricesRequestFailed && pricesError?.message ) }
It can be a small notice as currently the text is really ignorable and doesn't alert you at all, took me time to notice it appearing.

2023-05-16 07:59 UTC, Soare-Robert-Daniel commented
@HardeepAsrani, new look for error display

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/9c0b4efc-800a-41e7-bbba-179a2a7c5a45)

2023-05-16 10:27 UTC, HardeepAsrani approved these changes

2023-05-16 11:40 UTC, irinelenache commented
@Soare-Robert-Daniel Tested the enhancement and here is what i found:

- [ ] When i add the Stripe block and insert an invalid API key, the error won't be visible until i refresh the page https://vertis.d.pr/v/P5qeTx
- [ ] Saving the field without adding any content to it will throw a Wordpress error (can be seen in the previous video)
- [ ] There is an x button in the error and it's not doing anything https://vertis.d.pr/v/7G2dXX

2023-05-17 13:06 UTC, irinelenache commented
@Soare-Robert-Daniel Checked again and now the issues are fixed, thank you 🚀

2023-05-17 17:54 UTC, merged