Add support for more ACF fields in Dynamic Content
Codeinwp/otter-blocks pull request #1674
Opened 2023-05-25 15:27 UTC by Soare-Robert-Daniel

Closes https://github.com/Codeinwp/otter-internals/issues/83

### Summary

Added support for the following types:

	'button_group',
	'checkbox',
	'color_picker',
	'data_time_picker',
	'date_picker',
	'radio',
	'range',
	'select',
	'time_picker',
	'true_false',

### Screenshots 

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/3d8cbde8-b6d4-482e-b5bf-23c4c975b02b)

----

### Test instructions

🧪 Here are some ACF fields example. You can import them by going to the Tools tab in ACF menu.
[acf-export-2023-05-25.json.zip](https://github.com/Codeinwp/otter-blocks/files/11566554/acf-export-2023-05-25.json.zip)

Things to test:
- Dynamic to do break. We do not want any side effects.
- New ACF options do not break the page.

ℹ️ For most fields, we display the value ACF gives: email, URL, time, etc. But some areas are of type array like the Choice section, and they have the same option to display: value, label, or both. In the case of `both` options, we will use only the Label. That means `label` and `both` will have the same output.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/7edfc314-1523-43e2-940e-4a698a117b9d)

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/4023edb7-d8b2-4597-94c7-68c3f9d3ada1)

ℹ️ In case of values that are type array, each value will be displayed separated by a comma `,`

⚠️ If you do not have a value for the ACF field, the Dynamic Content `default` value will be used which is the text `Advanced Custom Fields`.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.
- [ ] PR is following [the best practices]()

2023-05-29 23:34 UTC, HardeepAsrani requested changes

2023-05-29 23:34 UTC, HardeepAsrani commented on plugins/otter-pro/inc/plugins/class-dynamic-content.php
> +			$meta = $meta ? __( 'True', 'otter-blocks' ) : __( 'False', 'otter-blocks' );
I think we can render "Yes" or "No" instead of True/False

2023-06-07 08:43 UTC, HardeepAsrani approved these changes

2023-06-22 07:47 UTC, rodica-andronache commented
@Soare-Robert-Daniel everything's working well now 👍

2023-07-10 10:56 UTC, merged