Add Module shortcut in Page
Codeinwp/otter-blocks pull request #1684
Opened 2023-05-31 11:28 UTC by Soare-Robert-Daniel

Closes #1540 .

### Summary

### Screenshots 

----

### Test instructions

https://github.com/Codeinwp/otter-blocks/assets/17597852/ea4c05fc-8be1-4d32-8f14-a5442641d5e7

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.
- [ ] PR is following [the best practices]()

2023-05-31 21:28 UTC, HardeepAsrani requested changes
I think you didn't understand what was being discussed in the issue. The toggle shouldn't enable/disable the module but give user an option to have any of those 4 block tools enabled by default if enabled.

For example, if the user toggles on the Blocks CSS, the Block CSS option will appear outside the Block Tools toggle.

Let me know if that makes it clear.

2023-06-08 12:11 UTC, HardeepAsrani requested changes

2023-06-08 12:11 UTC, HardeepAsrani commented on src/blocks/plugins/sticky/index.js
>  					label={ __( 'Transform to Sticky', 'otter-blocks' ) }
We can exclude this from the workflow. Right now, we enable Transform to Stick when you enable the tool, so it doesn't make sense to include this as default. No one wants to make Sticky as default. Plus, if you disable it then the Sticky settings are disabled too.

2023-06-12 15:04 UTC, HardeepAsrani commented on src/blocks/plugins/options/index.js
> +	select,
Is this needed?

2023-06-12 16:34 UTC, HardeepAsrani commented
Also, I see this when I try to use:

<img width="2195" alt="Screenshot 2023-06-12 at 10 04 30 PM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/8c2bb2cb-5f55-408d-928e-31930a68e6ea">

2023-06-13 07:04 UTC, Soare-Robert-Daniel commented on src/blocks/plugins/otter-tools-inspector/index.tsx
> +		console.count( 'Refresh Inspector' );
I would like to keep it for QA Team

2023-06-13 07:42 UTC, Soare-Robert-Daniel commented
@HardeepAsrani, I also added an E2E test for it now that we have the infrastructure.

2023-06-14 07:57 UTC, HardeepAsrani approved these changes

2023-06-14 11:08 UTC, irinelenache commented
@Soare-Robert-Daniel Tested and everything's fine here 🚀

2023-06-14 11:10 UTC, HardeepAsrani commented
@Soare-Robert-Daniel Can you remove debugging stuff so we can merge it?

2023-06-14 11:34 UTC, merged