feat: add hidden form field
Codeinwp/otter-blocks pull request #1728
Opened 2023-06-22 13:10 UTC by Soare-Robert-Daniel

Closes #.

### Summary

Add a field that is hidden from the client. Its function is to collect data from URLs to save metadata along with the submission.

URL example: `http://localhost:10007/496/form-hidden-field/?test=123`

### Screenshots 

#### Editor

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/1172c1ad-5ac3-41b5-a434-1d48b6a1cead)

#### Inspector

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/125ae402-1948-4ab7-8955-e60937de687f)

#### Frontend

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/d57ec784-6241-4811-a828-259c8d89117a)

#### Submission

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/286edaee-f085-4c3a-a030-596b115c77b8)

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.
- [ ] PR is following [the best practices]()

2023-06-23 03:25 UTC, HardeepAsrani commented on src/pro/blocks/form-hidden-field/edit.js
> +					</span>
As talked on Slack, we don't need to show this. We can simply show it like a normal field when Form block is selected and not show the block if isSelected is false.

2023-06-23 03:26 UTC, HardeepAsrani requested changes
Apart from mentioned, few things:

- The Block doesn't appear in the select list, nor the select list appear inside the block
<img width="282" alt="Screenshot 2023-06-23 at 8 56 06 AM" src="https://github.com/Codeinwp/otter-blocks/assets/2649903/0f03f620-68aa-4d56-8f45-0d777c74c928">

- If you click on Back to the Form button, it generates console errors.

2023-07-03 04:19 UTC, HardeepAsrani commented on src/blocks/blocks/form/hidden-field/inspector.js
> +					{ __( 'Back to the Form', 'otter-blocks' ) }
This still doesn't work for me.

2023-07-03 04:21 UTC, HardeepAsrani requested changes
Just a minor change and it should be good to go for QA.

2023-07-10 12:43 UTC, HardeepAsrani approved these changes

2023-07-14 12:09 UTC, rodica-andronache commented
@Soare-Robert-Daniel 

- [ ] when I activated Otter Pro, I got a fatal error https://vertis.d.pr/i/ewWgrU https://vertis.d.pr/i/1WZtgA
- [ ] in the free version, unlike the File field, which has its options disabled https://vertis.d.pr/i/iHWcCw, for the Hidden field the options can be edited sometimes https://vertis.d.pr/v/GcwqVy 
- [ ] in the free version, sometimes, after choosing the Hidden field you can't change that anymore, to other types of fields https://vertis.d.pr/v/cy58j5

2023-07-17 08:17 UTC, Soare-Robert-Daniel commented
> * [ ]  when I activated Otter Pro, I got a fatal error https://vertis.d.pr/i/ewWgrU https://vertis.d.pr/i/1WZtgA

I could not reproduce the fatal error.

2023-07-17 10:53 UTC, rodica-andronache commented
@Soare-Robert-Daniel I've tried again, and the fatal error is still happening for me. Maybe this video could help to see the exact steps I take ( the fatal error occurs after activating the license ) https://www.loom.com/share/62a6e77daaee48f09755eac2f562b008?sid=7619d799-4994-4b09-ba58-fc0541fc90e1
Let me know if there is something else I can share to help out. Thank you!

2023-07-17 11:57 UTC, HardeepAsrani commented
@Soare-Robert-Daniel I think it's because of the wrong name of the file: https://github.com/Codeinwp/otter-blocks/blob/feat/form-hidden-field/plugins/otter-pro/inc/render/class-form-hidden-block.pnp.php

It's `class-form-hidden-block.pnp.php` at this moment.

2023-07-17 13:09 UTC, Soare-Robert-Daniel commented
@HardeepAsrani thanks for info 🙏 . It seams that local tools did not find anything strange with that odd name.

Testing instance 

```
 Admin area URL: https://fiveact.s4-tastewp.com/wp-admin 
 Username: robertino 
 Password: pZ8pJCocVZI 
```

2023-07-17 20:59 UTC, rodica-andronache commented
@Soare-Robert-Daniel everything's working well 🚀

2023-07-25 03:09 UTC, merged