Add Webhook to Form
Codeinwp/otter-blocks pull request #1730
Opened 2023-06-28 13:52 UTC by Soare-Robert-Daniel

Closes #.

### Summary

Add Webhook triggers to Form.

### Screenshots 

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/91fc6a73-6e16-4e06-a1c0-8799b0080eae)

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/c79296f5-e1f6-4f9e-aa7b-dfe3272a521f)

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/48bb734d-6e52-467e-84c7-0defa68e2a6a)

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.
- [ ] PR is following [the best practices]()

2023-07-03 04:16 UTC, HardeepAsrani commented on plugins/otter-pro/inc/plugins/class-form-pro-features.php
> +	public function trigger_webhook( $form_data ) {
Just a reminder that we need to add a filter for the data being sent to webhook, with the webhook & form id being a parameter

2023-07-10 12:26 UTC, HardeepAsrani commented
@Soare-Robert-Daniel I tested it with Zapier and IFTTT, it works nicely. Here are few things we can do:

- Remove the `!` from Webhook Saved notification, just a NIT
- Add the filter as we discussed in L10 so people can modify the data that is sent to the hook.
- Have a small testing doc ready for QA and something that Docs team can use to create docs around this feature:
  - How to connect and use with IFTTT
  - How to connect and use with Zapier
  - How to use filter to modify the payload
- And we can also add a guidelink to the feature Form sidebar so people can see how it can be used.

Let me know your thoughts.

2023-07-12 14:33 UTC, HardeepAsrani commented on plugins/otter-pro/inc/plugins/class-form-pro-features.php
> +				$payload = apply_filters( 'themeisle_blocks_form_webhook_payload', array(), $form_data, $webhook );
A NIT: we can keep the same naming for filters as we do for rest of the code: https://github.com/Codeinwp/otter-blocks/blob/ce56737db046cb5d2bfad6af8656dec8fe1641be/inc/server/class-form-server.php#L241

2023-07-12 14:42 UTC, HardeepAsrani requested changes
Just some small changes and then we can put it for QA and docs creation.

2023-07-16 09:24 UTC, rodica-andronache commented
@Soare-Robert-Daniel I've tested both integrations (Zappier and IFTTT) and everything's working well 🚀

2023-07-17 11:55 UTC, merged