[Rock] Add PHP unit tests
Codeinwp/otter-blocks pull request #1824
Opened 2023-08-22 10:36 UTC by Soare-Robert-Daniel

Closes #1623

### Summary

Added units tests for:
- Dynamic Content query parse
- TBA

Locally the test can be run with Docker provided by Gutenberg packages.
```bash
npm run test:unit:php:setup # start the container
npm run test:unit:php:base # run the tests from `./tests` folder
```

### Test instructions

1. A slight change was made in Dynamic Content. Have a test instance with the current version, and after switching with the one from this PR, check if it still works.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.
- [ ] PR is following [the best practices]()

2023-09-19 17:53 UTC, HardeepAsrani requested changes
Can you fix the failing tests before putting it for review? Also, why do we have two separate unit tests actions?

2023-09-20 08:13 UTC, Soare-Robert-Daniel commented
I removed the old method. The old method was installing the test instance on the local machine. The new one will use a docker test instance provided by `wp-env` and `wp-scripts`.

2023-09-25 06:32 UTC, HardeepAsrani commented on tests/test-stripe-api-class.php
> +		}
Just a NIT, we can move this to the bootstrap class to avoid having to redefine it in some other test in future.

2023-09-25 06:33 UTC, HardeepAsrani approved these changes
LGTM, I've left a NIT but it looks good. We should get a good QA done on these features, Block Conditions in particular as I see there is some code change there to confirm that everything works just like before.

2023-09-25 06:33 UTC, HardeepAsrani commented on tests/test-stripe-api-class.php
> +// Replace with the correct namespace from your uploaded file.
```suggestion
```

2023-09-29 10:01 UTC, irinelenache commented
@Soare-Robert-Daniel Tested and everything's fine on my end 🚀

2023-11-02 06:08 UTC, merged