Improve issue handlers for Form submissions
Codeinwp/otter-blocks pull request #2266
Opened 2024-07-23 08:03 UTC by Soare-Robert-Daniel

Closes https://github.com/orgs/Codeinwp/projects/38/views/1?pane=issue&itemId=70294198

### Summary

- Improved the error messages when the tester is an admin.
- Added error log step for warnings.
- Code refactoring

### Screenshots 

#### Erorr displayed with admin details.

![image](https://github.com/user-attachments/assets/618a4eac-02b9-4a7c-a196-b88e20655224)

#### Issue logged in `debug.log`

```
[23-Jul-2024 07:57:13 UTC] [Otter Blocks][Form Block] Issue: Email could not be send. Might be an error with the service. The function `wp_mail` is not working properly. Please check the email provider settings.| Form data received: {"form_data":{"handler":"submit","payload":{"formInputsData":[{"label":"Form submission from","value":"http:\/\/localhost:10005\/form-block\/","metadata":{"position":"0"}},{"label":"(Field 1) Name","value":"yes","type":"text","id":"wp-block-themeisle-blocks-form-input-d8b68920","metadata":{"version":"1","position":"1","mappedName":""}}],"formOption":"1675009503e227cf028e7b282a731f32510ba3df_35c3d102","formId":"wp-block-themeisle-blocks-form-35c3d102","nonceValue":"5cbc632f7a","antiSpamTime":"166789","antiSpamHoneyPot":"","postUrl":"http:\/\/localhost:10005\/form-block\/","postId":"385"}},"uploaded_files_path":[],"files_loaded_to_media_library":[],"keep_uploaded_files":false,"metadata":[]}
```

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.
- [ ] PR is following [the best practices]()

2024-07-26 00:04 UTC, HardeepAsrani approved these changes

2024-07-30 16:35 UTC, carlalexander requested changes
No major thing here! I found a typo. 

As discussed, let's try to not use the modules with conventional commits. So just use `feat:`. But otherwise, the message is clear and good 🙌

2024-07-30 16:35 UTC, carlalexander commented on inc/server/class-form-server.php
> +		 * The flow fallows the railway programming pattern.
I think `fallows` is a typo 😅

2024-08-06 14:22 UTC, ineagu commented
looks good to me @Soare-Robert-Daniel

2024-08-06 14:55 UTC, merged