Adv-h-improv
Codeinwp/otter-blocks pull request #593
Opened 2021-11-02 10:01 UTC by Soare-Robert-Daniel

2021-11-05 19:50 UTC, HardeepAsrani requested changes
Few things:

- Can you make sure to check the backward compatibility with Advanced Headings made with previous Otter versions?
- Can you make sure that the clear button stays disabled if the value is the default.
- Can you make sure that the front-end CSS stays the same as this? I see the default in PHP for these values is still the same where we generated frontend CSS.
- Why did you remove the 0 default for`padding` but kept other padding-right/left as still zero?
- For the responsible controls, the reset should be for the selected view only not for all the views.
- In some components, there's already a Reset option so we should be using that instead of our own button: https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/range-control

2021-11-08 09:25 UTC, Soare-Robert-Daniel commented
> Few things:
> 
> * Can you make sure to check the backward compatibility with Advanced Headings made with previous Otter versions?

It works with the `dev` branch. No other changes have been made to this block so far in the last releases, so the users have the same version of the `dev`.
> * Can you make sure that the clear button stays disabled if the value is the default.

This works by default. 

```javascript
	padding: {
		type: 'number',
		default: 0
	},
```

The `ClearButton` sets the `padding` to `undefined`, but WP gives us `0` (since it is the default)  and not `undefined`.

This behavior is not visible at first. If you have a value, then reset, the `RangeControl` will show no value. If you save and reload the page, the `RangeControl` will show `0`.

> * Can you make sure that the front-end CSS stays the same as this? I see the default in PHP for these values is still the same where we generated frontend CSS.

I did not touch the PHP since the problem was reported in Editor. I will make the changes to match the Editor's behavior.

> * Why did you remove the 0 default for padding but kept other padding-right/left as still zero?

It was for some testing.
> * For the responsible controls, the reset should be for the selected view only not for all the views.

It does that.
`{ 'paddingTopTablet': 'Tablet' === getView && 'linked' !== attributes.paddingType },`
The attr `paddingTopTablet` will reset if the condition `'Tablet' === getView && 'linked' !== attributes.paddingType` is true.

> * In some components, there's already a Reset option so we should be using that instead of our own button: https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/range-control

I did not know about that. I will change it to this where is possible.

2021-11-09 13:14 UTC, irinelenache commented
@Soare-Robert-Daniel Tested this and didn't find any problem 👍

2021-11-10 18:09 UTC, HardeepAsrani approved these changes

2021-11-10 18:12 UTC, merged