Add new conditions to Visibility Conditions [WIP]
Codeinwp/otter-blocks pull request #753
Opened 2022-02-27 18:35 UTC by arinaturcu

#743, #750, #752

2022-03-01 06:12 UTC, HardeepAsrani commented
@arinaturcu Yesterday I left a couple of reviews above, I suppose I didn't mention your name so you didn't get the notification. The one about query string being a textarea needs to be done.

Also you can make Post Type as a Pro option.

I'm confused if Post Category should display if the page has all the selected categories or any of the selected. Any idea on how it's being done in Neve? We can make it consistent with Neve.

2022-03-01 07:49 UTC, HardeepAsrani requested changes

2022-03-01 13:24 UTC, arinaturcu commented
@HardeepAsrani Thank you for the review! :rocket: 

> I'm confused if Post Category should display if the page has all the selected categories or any of the selected. Any idea on how it's being done in Neve? We can make it consistent with Neve.

I looked a bit into Neve and it seems that just one category can be selected in a condition, but maybe I am missing something.
If you think that would be better if we displayed the block if it has any of the selected categories, let me know.

I managed all the other things you mentioned, hope I didn't miss anything. :eyes:

2022-03-02 12:29 UTC, HardeepAsrani commented on src/blocks/plugins/conditions/edit.js
> +		if ( 'queryString' === value ) {
Just a note that I've added the default value here. It was not working without it unless the user first changes the match value from one to another.

2022-03-02 12:30 UTC, HardeepAsrani commented
When you get time, can you @irinelenache QA this too? Thanks!

2022-03-07 10:22 UTC, irinelenache commented
@arinaturcu @HardeepAsrani Tested the features, here are my findings:

✅ The **Query string** conditions work as expected
✅ The **Post category** conditions work as expected

- [ ] For the **Post type** conditions, when i select more post types like [here](https://vertis.d.pr/3psDoo), the block is visible when only one of the selected post types is present, not both. (For the category conditions, all categories selected should be present in order for the block to be visible)

I couldn't test the visibility with blocks added as widgets. When i try to add any widget, i get an error in console https://vertis.d.pr/YWWDF0

Can be checked here:
```
 Admin area URL: https://likeswing.tastewp.com/wp-admin 
 Username: irinel 
 Password: aVUHGPPi3vQ 
```

Let me know if i missed anything, thank you 🚀

2022-03-07 12:45 UTC, HardeepAsrani commented
> I couldn't test the visibility with blocks added as widgets. When i try to add any widget, i get an error in console https://vertis.d.pr/YWWDF0

It should be fixed now. It was fixed in v2 branch so I've rebased this branch.

2022-03-07 14:24 UTC, arinaturcu commented
@irinelenache I think that a post can have a single type so it would not make much sense to check if a post has all the selected types.

@HardeepAsrani Please, let me know if I am wrong.
If I am right, then I will change the help text to something more suggestive.

2022-03-07 16:49 UTC, HardeepAsrani commented
@arinaturcu I agree with that. If people want, they can add multiple conditions to force that. Everything else works as expected @irinelenache?

2022-03-07 17:06 UTC, merged