Button group enhancements
Codeinwp/otter-blocks pull request #936
Opened 2022-05-20 18:15 UTC by arinaturcu

2022-05-30 09:10 UTC, arinaturcu commented
@HardeepAsrani @Soare-Robert-Daniel Do you have any ideas on how to shorten the CSS that I added in this PR?
I'm not really happy with it since there is some duplicated code, so if you think there are thing I can do to write it better let me know.

2022-06-22 20:03 UTC, arinaturcu commented
@HardeepAsrani Can you review the code here before handling this to QA?

2022-06-22 21:58 UTC, HardeepAsrani commented on src/blocks/blocks/button-group/group/inspector.js
> +					</Toolbar>
You don't need to make a new component here, there's one in Core that you can use already:

```
import { BlockAlignmentToolbar } from '@wordpress/block-editor';

<BlockAlignmentToolbar
	value={ value }
	isCollapsed={ false }
	controls={ [ 'left', 'center', 'right', 'full' ] }
	onChange={ () => {} }
/>
```

2022-06-23 18:09 UTC, HardeepAsrani requested changes
I've left a couple of comments on lines.

2022-06-24 15:24 UTC, arinaturcu commented
@HardeepAsrani Thank you! Working on it.

2022-06-24 18:50 UTC, arinaturcu commented on src/blocks/blocks/button-group/button/inspector.js
> +					title={ __( 'Types', 'otter-blocks' ) }
So there should be 4 styles: fill, outline, primary, and secondary?

2022-06-24 18:50 UTC, HardeepAsrani commented
@arinaturcu Yea, if the Neve is activated then we will have four, two of them will just inherit the Neve class.

2022-06-24 19:25 UTC, arinaturcu commented
@HardeepAsrani I make the changes, let me know if I missed anything :rocket:

2022-06-24 20:45 UTC, HardeepAsrani commented
@arinaturcu Just two changes:

- It might make more sense for the object attributes to be empty so we don't have an align-none class there, it should just be empty when nothing selected.
- If you've one alignment selected (say center) then clicking on it again should bring it back to the default state so user can unselect any selected alignment.

Apart from that, it all seems good and once you make the changes, you can put it for QA.

2022-06-26 11:02 UTC, arinaturcu commented
@HardeepAsrani
> * If you've one alignment selected (say center) then clicking on it again should bring it back to the default state so user can unselect any selected alignment.

This already happens, and by unselecting that one alignment, it selects the `none` one.
Also, the `none` alignment doesn't add an `align-none` class, it lets the block without any alignment class and can't be removed because of [this](https://github.com/WordPress/gutenberg/blob/c489f755eed1c6db6bad021562105caa19aad805/packages/block-editor/src/components/block-alignment-control/use-available-alignments.js#L17):
```
	// Always add the `none` option if not exists.
	if ( ! controls.includes( 'none' ) ) {
		controls = [ 'none', ...controls ];
	}
```
Let me know if I am mistaken :see_no_evil:

2022-06-26 16:05 UTC, HardeepAsrani commented
@arinaturcu thanks for correcting me. But I would still not like to see a None button as we don't need that, as you'd see in any core blocks.

Also, better to not have any defaults in attributes where possible.

2022-06-27 13:02 UTC, arinaturcu commented
@HardeepAsrani The `BlockAlignmentToolbar` doesn't allow to remove the None button, so to remove it I would have the following options:
- use the `AlignmentControl`, but it doesn't have a `full width` option, so I would add a separate control to enable that
- to write it from scratch, using `ToolbarGroup` similar to what I previously did

Let me know which way to proceed, or if you have another suggestion :rocket:

2022-06-28 04:21 UTC, HardeepAsrani commented
@arinaturcu I'll see if that is possible but for now I can't really use the PR, it throws an error in console and the block fails.

2022-06-28 07:49 UTC, arinaturcu commented
@HardeepAsrani Yes, sorry, forgot to push some changes.

2022-06-28 13:44 UTC, irinelenache commented
@arinaturcu Tested and found this:

- [ ] When i try to change the alignment, nothing happens and i'm getting errors in customizer https://vertis.d.pr/rv2WgE

2022-06-28 15:38 UTC, arinaturcu commented
Thank you @irinelenache :rocket: 
The issue should be fixed now.

2022-06-29 07:02 UTC, irinelenache commented
@arinaturcu Thank you, the error is fixed now 🚀 

Some other findings:

- [ ] The button spacing is not applied in editor when the preview is in tablet/mobile mode https://vertis.d.pr/44snk3
- [ ] The alignments don't work as expected when the buttons are collapsed on mobile, i made a video to better outline the issue https://vertis.d.pr/CqWbpC

You can check the issues here:
```
 Admin area URL: https://otter2.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: 3hm5qSjv4lc 
```

2022-06-29 07:03 UTC, HardeepAsrani commented
> The button spacing is not applied in editor when the preview is in tablet/mobile mode https://vertis.d.pr/44snk3

This is being fixed in the FSE PR already, not related to this PR.

2022-06-29 11:16 UTC, arinaturcu commented
@irinelenache The first one is related to another PR as Hardeep said, and the second one should be fixed now.
Thank you! :rocket:

2022-06-29 12:18 UTC, irinelenache commented
@arinaturcu Tested again and now everything works fine, will move this to **Ready to merge** 🚀

2022-06-29 12:46 UTC, merged