Add condition to Animation loading.
Codeinwp/otter-blocks pull request #957
Opened 2022-05-30 13:44 UTC by Soare-Robert-Daniel

Closes #927

2022-05-30 13:47 UTC, HardeepAsrani commented
@Soare-Robert-Daniel You can have one static variable to keep track of what has already been loaded so you don't have to do the comparison for each block for the asset has already been loaded.

2022-05-30 13:50 UTC, Soare-Robert-Daniel commented
> @Soare-Robert-Daniel You can have one static variable to keep track of what has already been loaded so you don't have to do the comparison for each block for the asset has already been loaded.

Is there a possibility that the variable to collide in 2 simultaneous requests? I request A has Count, but request B does not have it. Is there a change that B to use the values from A?

2022-05-30 13:54 UTC, selul commented
> Is there a possibility that the variable to collide in 2 simultaneous requests? 

Nope.

2022-05-30 14:01 UTC, selul requested changes

2022-05-30 14:01 UTC, selul commented on inc/class-blocks-animation.php
> +		if( strpos( $block_content, 'animated' ) && ! self::$scripts_loaded['animation'] ) {
I would add the flag first and after the strpos since the condition, in this way the strpos is no longer executed once the flag is added.

2022-05-30 14:12 UTC, selul requested changes
Nice work, Robert!

2022-05-30 14:12 UTC, selul approved these changes

2022-06-15 12:28 UTC, irinelenache commented
@Soare-Robert-Daniel Tested and it works fine, both for previously/new created blocks 🚀 

Found only a strange thing:

- [ ] **anim-typing** and **anim-count** scripts are loaded on the **Blog** page https://vertis.d.pr/WmGGc9 . I don't know if this should be the expected behaviour

You can check the issue here:
```
 Admin area URL: https://snottychair.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: e_rpN7u9PxE 
```

2022-06-15 22:33 UTC, HardeepAsrani commented
@Soare-Robert-Daniel For the archive pages, you can use a solution maybe similar to this if nothing else works out: https://github.com/Codeinwp/otter-blocks/blob/master/inc/class-registration.php#L275-L285

2022-06-16 10:51 UTC, Soare-Robert-Daniel commented
> @Soare-Robert-Daniel For the archive pages, you can use a solution maybe similar to this if nothing else works out: https://github.com/Codeinwp/otter-blocks/blob/master/inc/class-registration.php#L275-L285

I do not see how to do something similar in this function https://github.com/Codeinwp/otter-blocks/blob/d2370d9f58125528b0def418ea7bd31c48f6aede/inc/class-blocks-animation.php#L88

2022-06-16 21:26 UTC, HardeepAsrani commented
> anim-typing and anim-count scripts are loaded on the Blog page https://vertis.d.pr/WmGGc9 . I don't know if this should be the expected behaviour

In your blog posts, one of the post being displayed in the loop probably uses those features and that's why it's showing. Can you confirm that?

Second @Soare-Robert-Daniel, the `animate.compact.css` and `build/animation/index.css` need to load in the backend too, so the animations aren't working in the backend + the styles in the animation popup look odd.

2022-06-16 21:27 UTC, HardeepAsrani requested changes
As mentioned in the last comment.

2022-06-16 21:28 UTC, HardeepAsrani commented
@irinelenache 

> anim-typing and anim-count scripts are loaded on the Blog page https://vertis.d.pr/WmGGc9 . I don't know if this should be the expected behaviour

In your blog posts, one of the post being displayed in the loop probably uses those features and that's why it's showing. Can you confirm that?

2022-06-17 10:17 UTC, Soare-Robert-Daniel commented
> In your blog posts, one of the post being displayed in the loop probably uses those features and that's why it's showing. Can you confirm that?

Some of the posts have a block that the plugins. They are used as excerpts, but the tags are stripped. This might mean it is passing through `render_blocks` (triggering the loading).

Ref: https://cs.github.com/?scope=org%3ACodeinwp&scopeName=Codeinwp&q=excerpt-wrap+entry-summary

2022-06-17 18:54 UTC, HardeepAsrani commented
@Soare-Robert-Daniel 

After your last commits, I get this error if I just preview a post:

`Notice: Undefined variable: post in /var/www/html/wp-content/plugins/otter-blocks/inc/class-blocks-animation.php on line 120 Call Stack: 0.0237 360032 1. {main}() /var/www/html/index.php:0 0.0285 360312 2. require('/var/www/html/wp-blog-header.php') /var/www/html/index.php:17 3.8157 13541552 3. require_once('/var/www/html/wp-includes/template-loader.php') /var/www/html/wp-blog-header.php:19 3.8406 13592632 4. include('/var/www/html/wp-content/themes/neve/single.php') /var/www/html/wp-includes/template-loader.php:106 3.8415 13594136 5. get_header($name = ???, $args = ???) /var/www/html/wp-content/themes/neve/single.php:11 3.8418 13594512 6. locate_template($template_names = [0 => 'header.php'], $load = TRUE, $require_once = TRUE, $args = []) /var/www/html/wp-includes/general-template.php:48 3.8419 13594592 7. load_template($_template_file = '/var/www/html/wp-content/themes/neve/header.php', $require_once = TRUE, $args = []) /var/www/html/wp-includes/template.php:716 3.8422 13595040 8. require_once('/var/www/html/wp-content/themes/neve/header.php') /var/www/html/wp-includes/template.php:770 3.8442 13596496 9. wp_head() /var/www/html/wp-content/themes/neve/header.php:46 3.8442 13596496 10. do_action($hook_name = 'wp_head') /var/www/html/wp-includes/general-template.php:3042 3.8442 13596872 11. WP_Hook->do_action($args = [0 => '']) /var/www/html/wp-includes/plugin.php:476 3.8442 13596872 12. WP_Hook->apply_filters($value = '', $args = [0 => '']) /var/www/html/wp-includes/class-wp-hook.php:331 3.8472 13600296 13. wp_enqueue_scripts('') /var/www/html/wp-includes/class-wp-hook.php:307 3.8472 13600296 14. do_action($hook_name = 'wp_enqueue_scripts') /var/www/html/wp-includes/script-loader.php:2156 3.8472 13600672 15. WP_Hook->do_action($args = [0 => '']) /var/www/html/wp-includes/plugin.php:476 3.8472 13600672 16. WP_Hook->apply_filters($value = '', $args = [0 => '']) /var/www/html/wp-includes/class-wp-hook.php:331 3.8472 13601800 17. wp_common_block_scripts_and_styles('') /var/www/html/wp-includes/class-wp-hook.php:307 3.8473 13601800 18. do_action($hook_name = 'enqueue_block_assets') /var/www/html/wp-includes/script-loader.php:2352 3.8473 13602176 19. WP_Hook->do_action($args = [0 => '']) /var/www/html/wp-includes/plugin.php:476 3.8473 13602176 20. WP_Hook->apply_filters($value = '', $args = [0 => '']) /var/www/html/wp-includes/class-wp-hook.php:331 3.8620 13613640 21. ThemeIsle\GutenbergBlocks\Blocks_Animation->enqueue_block_frontend_assets('') /var/www/html/wp-includes/class-wp-hook.php:307 `

Don't know why you added a `$can_load_frontend` as it's just making things more complex, code without it looked much cleaner. 😄

2022-06-20 06:57 UTC, Soare-Robert-Daniel commented
@HardeepAsrani I do not get the error.

With `$can_load_frontend` I tried to add the loading condition that I removed on refactor. I do not know if it is more complex. We can not make a full check every time `render_block` is called.

Even so, the conditions still not remove the scripts loaded when Neve posts are rendered or our own Posts block or Query Loop block. Also, all the frontend scrips have the same behaviour.

![image](https://user-images.githubusercontent.com/17597852/174542310-e966dc11-d4b1-4b86-be02-d0a2710eadc4.png)

Any idea on how we check if the block is used as post description in Posts blocks or Query Loop or Neve?

2022-06-21 03:32 UTC, HardeepAsrani commented
> Any idea on how we check if the block is used as post description in Posts blocks or Query Loop or Neve?

Not really, you can't do much about it. It's fine to leave it that way.

2022-06-21 03:34 UTC, HardeepAsrani commented on inc/class-blocks-animation.php
> +		if ( is_singular() && strpos( get_the_content( null, false, $post ), '<!-- wp:' ) === false ) {
That error still appears if I preview or view a post. This happens because $post isn't defined anywhere. @Soare-Robert-Daniel

2022-06-21 12:25 UTC, HardeepAsrani requested changes
@Soare-Robert-Daniel That issue is fixed but the frontend.js isn't enqueued in the front which is a part of CSS animations that helps us to trigger the animation on page scroll.

While you're at it, can you also do this in this PR? https://github.com/Codeinwp/otter-blocks/issues/938

We load multiple CSS files in the front for CSS animations, it can be just a single file using webpack.

2022-06-21 15:12 UTC, HardeepAsrani approved these changes

2022-06-21 15:13 UTC, merged